[package]
name = "wasm-soft-float-utils"
description = "Basic operations for wasm soft-float backends"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
quickcheck = "1.0"
